[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "0.82.0", features = ["oapi", "serve-static"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing-subscriber = "0.3"
